class DnsLineList_Volc:
    line_list = {}


class VOLC_CONSTANT:
    """Volc OpenApi Constant"""

    # URL path
    VOLC_URL_PATH = "/"

    # API Version
    VERSION = "2021-07-05"

    # Method
    GET = "get"
    POST = "post"


class VOLC_DOMAIN_CONSTANT:
    """
    AccessKeyID: AKLTYThmM2IzNzM4ZTg5NGZiMmEzN2MwMzNlNGQ1OTQzNWU
    SecretAccessKey: TnpnMk1UazRZemRrWlRVd05ESmxaV0kzTldZd1pUWmpNbVkyTkRkak1qVQ==
    """
    """
    AK = "AKLTZDRjOWFkYzZlOWRlNGEwY2E2Yjg3OTMyZDM5NzRlMDY"
    SK = "WXpSbE1XWXlaams1T0daaE5EY3dPRGt3TldWbU9UQmpOelZrTjJZeE1XWQ=="
    """
    AK = "AKLTYThmM2IzNzM4ZTg5NGZiMmEzN2MwMzNlNGQ1OTQzNWU"
    SK = "TnpnMk1UazRZemRrWlRVd05ESmxaV0kzTldZd1pUWmpNbVkyTkRkak1qVQ=="
    AK_ONLINE = "AKLTNDU4YmMxNDBiYWYxNDBjZTljYjhlYzRjY2I5N2UzMjk"
    SK_ONLINE = "TjJNeFlUWTBNVFE1TW1SaE5EYzNOamd4TURJek9UUmlPREUyT0RSbE5Uaw=="
    REGION = "cn-north-1"
    SERVICE = "domain_service"
    VERSION = "2021-06-01"
    # """提交实名认证资料"""
    # UploadDomainAuthenticationInfo = "UploadDomainAuthenticationInfo"
    """批量续费域名"""
    BatchRenew = "BatchRenew"
    """注册域名"""
    RegisterDomain = "RegisterDomain"
    """续费域名"""
    RenewDomain = "RenewDomain"
    """域名赎回"""
    RestoreDomain = "RestoreDomain"
    """获取模板列表"""
    ListTemplates = "ListTemplates"
    """获取模板详情"""
    GetTemplates = "GetTemplate"
    """删除用户模板"""
    DelTemplate = "DeleteTemplate"
    """更新模板详情"""
    UpdateTemplate = "UpdateTemplate"
    # """获取域名列表"""
    # ListDomains = "ListDomains"
    """获取购物车列表（获取域名清单）"""
    ListShopping = "GetShoppingList"
    """添加购物车"""
    AddShopping = "AddDomainToShoppingList"
    """批量添加购物车(添加域名清单)"""
    BatchAddDomainToShoppingList = "BatchAddDomainToShoppingList"
    """删除购物车（删除清单表中的某个域名）"""
    DelShopping = "RemoveDomainFromShoppingList"
    """清空购物车"""
    ClearShoppingList = "ClearShoppingList"
    """获取模板列表"""
    ListTemplate = "GetTemplateList"
    """域名转入"""
    TransferIn = "TransferIn"
    """域名转入检查"""
    TransferInCheck = "TransferInCheck"
    """续费信息校验"""
    RenewCheck = "RenewCheck"
    """单个域名询价"""
    QuerySingleDomainPrice = "QuerySingleDomainPrice"
    """域名证书下载"""
    DownloadDomainCertImage = "DownloadDomainCertImage"
    """Whois查询"""
    Whois = "Whois"
    """设置/取消域名转移锁"""
    SetTransferProhibition = "SetTransferProhibition"
    """设置/取消域名更新锁"""
    SetUpdateProhibition = "SetUpdateProhibition"
    """域名过户"""
    ChangeOwnership = "ChangeOwnership"
    """数据概览"""
    Overview = "Overview"
    """修改域名权威NS"""
    ModifyDomainNS = "ModifyDomainNS"
    """导出域名列表"""
    ExportDomains = "ExportDomains"
    """同步dns_host"""
    SyncDNSHost = "SyncDNSHost"
    """获取dns_host列表"""
    ListDNSHost = "ListDNSHost"
    """增加dns_host"""
    AddDNSHost = "AddDNSHost"
    """更新dns_host"""
    UpdateDNSHost = "UpdateDNSHost"
    """删除dns_host"""
    DeleteDNSHost = "DeleteDNSHost"
    """修改域名备注"""
    ModifyDomainComments = "ModifyDomainComments"
    """检查域名列表是否属于账号"""
    CheckAccountDomainList = "CheckAccountDomainList"
    """获取域名证书的图片"""
    DownloadDomainCertImage = "DownloadDomainCertImage"
    """域名证书下载"""
    DownloadDomainCert = "DownloadDomainCert"
    """批量过户"""
    BatchRegistrantChange = "BatchRegistrantChange"
    """批量ns修改"""
    BatchModifyDomainNS = "BatchModifyDomainNS"
    """修改域名联系人信息"""
    ModifyDomainContactorInfo = "ModifyDomainContactorInfo"
    """获取操作记录详情"""
    GetOperation = "GetOperation"
    """获取域名详情"""
    GetDomain = "GetDomain"
    """获取操作记录列表"""
    ListOperateList = "ListOperateList"
    """获取域名列表"""
    ListDomains = "ListDomains"
    """提交域名实名认证资料"""
    UploadDomainAuthenticationInfo = "UploadDomainAuthenticationInfo"
    """软删除域名"""
    DeleteDomain = "DeleteDomain"


class VOLC_DOMAIN_CONSTANT_OPENAPI:
    # gogokid
    AK = "AKLTYThmM2IzNzM4ZTg5NGZiMmEzN2MwMzNlNGQ1OTQzNWU"
    SK = "TnpnMk1UazRZemRrWlRVd05ESmxaV0kzTldZd1pUWmpNbVkyTkRkak1qVQ=="
    # Domaintest1
    AK_Domaintest1 = "AKLTZDU3YjgzMTY3NmRmNDVhYjg4MGEwODFkMWFhMGU0NDg"
    SK_Domaintest1 = "WVdJeU5HUmlZalJpTTJRd05ESm1ZMkl6TlRRMFlUQm1aR0V4TVRGaFpqUQ=="

    AK_ONLINE = "AKLTNDU4YmMxNDBiYWYxNDBjZTljYjhlYzRjY2I5N2UzMjk"
    SK_ONLINE = "TjJNeFlUWTBNVFE1TW1SaE5EYzNOamd4TURJek9UUmlPREUyT0RSbE5Uaw=="
    # Domaintest2
    # AK = AKLTZGNmNmY2Yjk1YWE5NDI1MWFkZjU3NGRhMjQ0NDUyNDA
    # T0RkbE5UVmpNV1JsT0RkbU5HRmxZamcwTXpKa05URmtZVGRrTWpka01UUQ==
    REGION = "cn-north-1"
    SERVICE = "domain_openapi"
    VERSION = "2022-12-12"
    """openapi域名询价"""
    Checkfee = "CheckFee"
    """openapi获取域名列表"""
    ListDomains = "ListDomains"
    """openapi异步注册域名"""
    RegisterDomain = "RegisterDomain"
    """获取异步任务结果"""
    GetAsyncTask = "GetAsyncTask"
