class CONSTANT:
    renewal_fee = {
        '.ac.cn': '38',
        '.art': '97',
        '.auto': '16900',
        '.biz': '102',
        '.black': '319',
        '.cc': '39',
        '.center': '59',
        '.chat': '60',
        '.city': '125',
        '.cloud': '121',
        '.club': '76',
        '.cn': '38',
        '.co': '169',
        '.com': '69',
        '.com.cn': '38',
        '.company': '39',
        '.cool': '189',
        '.design': '305',
        '.email': '129',
        '.fun': '54',
        '.fund': '305',
        '.gold': '46',
        '.gov.cn': '109',
        '.group': '50',
        '.guru': '189',
        '.host': '46',
        '.info': '98',
        '.ink': '178',
        '.life': '50',
        '.link': '72',
        '.live': '130',
        '.love': '185',
        '.ltd': '108',
        '.mobi': '119',
        '.net': '76',
        '.net.cn': '38',
        '.online': '53',
        '.org.cn': '38',
        '.plus': '196',
        '.press': '109',
        '.pro': '96',
        '.pub': '189',
        '.red': '106',
        '.ren': '41',
        '.run': '129',
        '.shop': '218',
        '.show': '55',
        '.site': '52',
        '.social': '60',
        '.space': '128',
        '.store': '59',
        '.team': '189',
        '.tech': '50',
        '.today': '130',
        '.top': '28',
        '.tv': '199',
        '.video': '138',
        '.vip': '36',
        '.wang': '45',
        '.website': '46',
        '.work': '33',
        '.world': '189',
        '.xyz': '72',
        '.zone': '55',
        '.餐厅': '3860',
        '.佛山': '339',
        '.公司': '98',
        '.集团': '10000',
        '.手机': '2950',
        '.网店': '1280',
        '.网络': '98',
        '.网址': '2800',
        '.我爱你': '57',
        '.在线': '1980',
        '.招聘': '3860',
        '.中国': '98',
        '.中文网': '2800',
        '.中文.art': '97',
        '.中文.biz': '102',
        '.中文.cc': '39',
        '.中文.center': '59',
        '.中文.chat': '60',
        '.中文.city': '125',
        '.中文.cn': '38',
        '.中文.com': '69',
        '.中文.company': '39',
        '.中文.cool': '189',
        '.中文.email': '129',
        '.中文.fun': '54',
        '.中文.fund': '305',
        '.中文.gold': '46',
        '.中文.group': '50',
        '.中文.guru': '189',
        '.中文.life': '50',
        '.中文.live': '42',
        '.中文.ltd': '108',
        '.中文.net': '76',
        '.中文.online': '53',
        '.中文.plus': '196',
        '.中文.pub': '189',
        '.中文.ren': '41',
        '.中文.run': '129',
        '.中文.shop': '218',
        '.中文.show': '55',
        '.中文.site': '52',
        '.中文.social': '60',
        '.中文.space': '128',
        '.中文.store': '59',
        '.中文.team': '189',
        '.中文.tech': '50',
        '.中文.today': '130',
        '.中文.top': '28',
        '.中文.tv': '199',
        '.中文.wang': '45',
        '.中文.world': '189',
        '.中文.xyz': '72',
        '.中文.zone': '55',
        '.中文.餐厅': '3860',
        '.中文.佛山': '339',
        '.中文.公司': '220',
        '.中文.集团': '10000',
        '.中文.手机': '2950',
        '.中文.网店': '1280',
        '.中文.网络': '106',
        '.中文.网址': '2800',
        '.中文.我爱你': '58',
        '.中文.在线': '1980',
        '.中文.招聘': '3860',
        '.中文.中国': '98',
        '.中文.中文网': '2800',
    }


import base64
import os


def image_file(imageName):
    """
    fm: 图片名称
    """
    """查找图片进行base64处理"""
    for path, d, filelist in os.walk(
            "/Users/bytedance/PycharmProjects/Domain_API/test_cases/image_file"):  # Debug_path
        # "trademarkTest"):  # Tesla_path
        for filename in filelist:
            if imageName != "":
                if filename.startswith(imageName):
                    with open(os.path.join(path, filename), 'rb') as f:
                        img_data = f.read()
                        return "data:image/jpeg;base64," + base64.b64encode(img_data).decode("utf-8")
            else:
                return "请检查文件名称"


print(image_file(""))
